name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main

jobs:
  sbt-build:
    runs-on: buildjet-32vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: coursier/cache-action@v6.3
      - uses: olafurpg/setup-scala@v13
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build and Test
        run: sbt test
